//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_tbl
    {
        public int TaskId { get; set; }
        public int EmpId { get; set; }
        public string TaskName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public decimal ConsumedHours { get; set; }
        public decimal EstimatedHours { get; set; }
        public System.DateTime TaskDate { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Deviation { get; set; }
    }
}
